### Get All product

GET http://localhost:4000/api/products HTTP/1.1

### Get Single Product

GET   http://localhost:4000/api/products/60punmmiee7899 HTTP/1.1

### Add item

POST http://localhost:4000/api/products HTTP/1.1

Content-Type: application/json

body : {
   "title" : "Hello Mhjjk",
   "price" : "RS. 1000000000000000001",
   "image" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fblogs.sap.com%2Fwp-content%2Fuploads%2F2012%2F06%2Fabapdevelopmenttoolsforsapnetweaver_114598.png&tbnid=_q4iUPPBMhscJM&vet=12ahUKEwi8krrqsYv-AhVcF7cAHWQ2DLoQMygAegUIARDBAQ..i&imgrefurl=https%3A%2F%2Fblogs.sap.com%2F2012%2F06%2F19%2Fget-started-with-the-abap-development-tools-for-sap-netweaver%2F&docid=_wVi0S_6f8rM5M&w=600&h=317&q=SAP%20ABAP%20development&ved=2ahUKEwi8krrqsYv-AhVcF7cAHWQ2DLoQMygAegUIARDBAQ",
   "details" : "Just"
}
### update item


PUT http://localhost:4000/api/products/642995182c1a17d6cda0f53a HTTP/1.1

Content-Type: application/json
 {
   "title" : "Hello Bro",

}

### delete

delete http://localhost:4000/api/products/642995182c1a17d6cda0f53a HTTP/1.1